movies/main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('film/<slug:slug>', views.FilmDeatilView.as_view(), name='movie-detail'),
    path('movies-rec', views.movies_rec, name='movies-rec'),
    path('movie-list/', views.movie_list, name='movie-list')
]

movies/movies/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('profile/', include(('user.urls', 'user'), namespace='user')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('genre-selection/', views.genre_selection, name='genre_selection'),
]

movies/main/models.py
from django.db import models
from slugify import slugify
from django.urls import reverse



class Actor(models.Model):
    name = models.CharField('Имя', max_length=100)
    surname = models.CharField('Фамилия', max_length=150)

    def __str__(self):
        return self.name + " " + self.surname

    class Meta:
        verbose_name = 'Актер'
        verbose_name_plural = 'Актеры'

class Genre(models.Model):
    name = models.CharField('Название', max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Director(models.Model):
    name = models.CharField('Имя', max_length=100)
    surname = models.CharField('Фамилия', max_length=150)

    def __str__(self):
        return self.name + " " + self.surname

    class Meta:
        verbose_name = 'Режиссер'
        verbose_name_plural = 'Режиссеры'

class Country(models.Model):
    name = models.CharField('Название', max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'


class Film(models.Model):
    title = models.CharField('Название', max_length=150)
    country = models.ManyToManyField(Country)
    year = models.PositiveSmallIntegerField('Год')
    genre = models.ManyToManyField(Genre)
    directors = models.ManyToManyField(Director)
    actors = models.ManyToManyField(Actor)
    rating = models.FloatField('Рейтинг')
    description = models.TextField('Описание')
    poster = models.URLField('Постер')
    slug = models.SlugField(max_length=150,unique=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Film, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'

movies/main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.utils.decorators import method_decorator

from .models import Actor, Genre, Director, Film, Country
from django.views.generic import DetailView, TemplateView, ListView
from slugify import slugify
from django.views import View
from django.http import JsonResponse

from user.models import UserProfile, Enrollment



class IndexView(TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
      
        if self.request.user.is_authenticated:
            user_profile = UserProfile.objects.get(user=self.request.user)
            user_genres = user_profile.genres.all()
            films_on_genre = Film.objects.filter(genre__in=user_genres)[:10]
            context['films_on_genre'] = films_on_genre
        context['films'] = Film.objects.all()[:10]
        context['genres'] = Genre.objects.all()
        context['show_genre_modal'] = self.request.session.pop('show_genre_modal', False)
        return context


class FilmDeatilView(DetailView):
    model = Film
    template_name = 'main/movie-detail.html'
    context_object_name = 'film'

    def post(self, request, slug):
        film = self.get_object()
        is_viewed = request.POST.get('is_viewed') == 'true'  

        enrollment, created = Enrollment.objects.get_or_create(user=request.user.userprofile, film=film)
        enrollment.isViewed = is_viewed
        enrollment.save()

        return JsonResponse({'status': 'success'})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_authenticated:
            film = self.get_object()
            enrollment = Enrollment.objects.filter(user__user=user, film=film).first()
            context['enrollment'] = enrollment
        return context

def movie_list(request):
    genres = request.GET.get('genres')
    years = request.GET.get('years')
    films = Film.objects.all()

    if genres:
        genre_list = [int(genre) for genre in genres.split(',')]
        films = films.filter(genre__in=genre_list)

    if years:
        year_list = [int(year) for year in years.split(',')]
        films = films.filter(year__in=year_list)
    films = films.distinct()
    data = {
        'films': films
    }
    return render(request, 'main/movie-list.html', data)

def movies_rec(request):
    genres = Genre.objects.all().order_by('name')
    films = Film.objects.all()
    years = Film.objects.values_list('year', flat=True).distinct().order_by('-year')
    return render(request, 'main/movies-rec.html', {'genres': genres, 'films': films, 'years': years})

movies/main/templates/main/index.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}MovieFinder{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'main/css/movies-style.css' %}">
{% endblock %}

{% block content %}
<img src="{% static 'main/img/logo.png' %}" alt="logo" class="img-fluid">
    <div class="container mt-5">
        <!-- Горизонтальный скроллинг с постерами фильмов -->
        <div class="container mt-5 position-relative">
            <div style="margin: 10px; display:inline-block, grid; max-width: 1000px;">
                <big>Лучшие фильмы</big>
<!--                <a href="{% url 'main:movies-rec' %}" class="btn btn-light" style="text-align: right;">Смотреть все</a>-->
            </div>
            <button class="btn btn-secondary position-absolute top-50 start-0 translate-middle-y" onclick="scrollMovies('left')">&#8592;</button>
            <div class="row flex-row flex-nowrap overflow-auto" id="moviesRow">
                {% for film in films %}
                <div class="col-6 col-sm-4 col-md-3">
                    <div class="card bg-dark text-light mb-3" id="movie-card">
                        <img src="{{ film.poster }}" class="card-img-top" data-bs-toggle="modal" data-bs-target="#movieModal{{ film.id }}" alt="{{ film.title }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ film.title }}</h5>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <button class="btn btn-secondary position-absolute top-50 end-0 translate-middle-y" onclick="scrollMovies('right')">&#8594;</button>
        </div>
    </div>

{%if request.user.is_authenticated %}
    {% if films_on_genre|length > 0 %}
    <div class="container mt-5">
        <!-- Горизонтальный скроллинг с постерами фильмов -->
        <div class="container mt-5 position-relative">
            <div style="margin: 10px; display:inline-block, grid; max-width: 1000px;">
                <big>Эксклюзивно для Вас</big>
<!--                <a href="{% url 'main:movies-rec' %}" class="btn btn-light" style="text-align: right;">Смотреть все</a>-->
            </div>
            <button class="btn btn-secondary position-absolute top-50 start-0 translate-middle-y" onclick="scrollMovies('left')">&#8592;</button>
            <div class="row flex-row flex-nowrap overflow-auto" id="moviesRow">
                {% for film in films_on_genre %}
                <div class="col-6 col-sm-4 col-md-3">
                    <div class="card bg-dark text-light mb-3" id="movie-card">
                        <img src="{{ film.poster }}" class="card-img-top" data-bs-toggle="modal" data-bs-target="#movieModal{{ film.id }}" alt="{{ film.title }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ film.title }}</h5>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <button class="btn btn-secondary position-absolute top-50 end-0 translate-middle-y" onclick="scrollMovies('right')">&#8594;</button>
        </div>
    </div>
    {% endif %}
{%endif%}

<!-- Movie Modal -->
    {% for film in films_on_genre %}
    <div class="modal fade" id="movieModal{{ film.id }}" tabindex="-1" aria-labelledby="movieModalLabel{{ film.id }}" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content bg-dark text-light">
                <div class="modal-header">
                    <h5 class="modal-title" id="movieModalLabel{{ film.id }}">{{ film.title }}</h5>
                    <button type="button" class="btn-close text-light" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-4">
                            <img src="{{ film.poster }}" class="img-fluid" alt="{{ film.title }}">
                        </div>
                        <div class="col-md-8">
                            <p>Оценка: {{ film.rating }}/10</p>
                            <p>Описание фильма: {{ film.description }}</p>
                            <a href="{% url 'main:movie-detail' film.slug %}" class="btn btn-light">Подробнее</a>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

 <!-- Movie Modal -->
    {% for film in films %}
    <div class="modal fade" id="movieModal{{ film.id }}" tabindex="-1" aria-labelledby="movieModalLabel{{ film.id }}" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content bg-dark text-light">
                <div class="modal-header">
                    <h5 class="modal-title" id="movieModalLabel{{ film.id }}">{{ film.title }}</h5>
                    <button type="button" class="btn-close text-light" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-4">
                            <img src="{{ film.poster }}" class="img-fluid" alt="{{ film.title }}">
                        </div>
                        <div class="col-md-8">
                            <p>Оценка: {{ film.rating }}/10</p>
                            <p>Описание фильма: {{ film.description }}</p>
                            <a href="{% url 'main:movie-detail' film.slug %}" class="btn btn-light">Подробнее</a>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

   <!-- Genre Modal -->
    <div class="modal fade" id="genreModal" tabindex="-1" aria-labelledby="genreModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content bg-dark text-light">
                <div class="modal-header">
                    <h5 class="modal-title" id="genreModalLabel">Выберите ваши любимые жанры</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!-- Форма выбора жанров -->
                    <form id="genreForm" method="post" action="{% url 'user:genre_selection' %}">
                        {% csrf_token %}
                        <div class="row">
                            {% for genre in genres %}
                                <div class="col-6 col-md-4 col-lg-3">
                                    <div class="form-check">
                                        <input class="form-check-input genre-checkbox" type="checkbox" value="{{ genre.id }}" name="genres" id="genre{{ genre.id }}">
                                        <label class="form-check-label genre-label" for="genre{{ genre.id }}">{{ genre.name }}</label>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Получение CSRF-токена из cookies
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Имя cookie совпадает с именем CSRF-токена
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        window.addEventListener('DOMContentLoaded', function () {
            {% if show_genre_modal %}
                $('#genreModal').modal('show');  // Открытие модального окна с выбором жанров
            {% endif %}

            // Обработчик клика на квадратик с жанром
            $('.genre-item').on('click', function () {
                $(this).toggleClass('selected');  // Добавление/удаление класса selected при выборе/снятии выбора
            });

            // Обработчик отправки формы выбора жанров
            $('#genreForm').on('submit', function (e) {
                e.preventDefault();  // Отмена стандартного действия формы

                var selectedGenres = [];  // Массив для хранения выбранных жанров

                $('.genre-checkbox:checked').each(function () {
                    selectedGenres.push($(this).val());  // Добавление ID выбранного жанра в массив
                });

                console.log(selectedGenres);

                // Получение CSRF-токена
                var csrfToken = getCookie('csrftoken');

                // Отправка данных на сервер
                $.ajax({
                    url: '{% url 'user:genre_selection' %}',
                    method: 'GET',
                    headers: { 'X-CSRFToken': csrfToken },  // Передача CSRF-токена в заголовках запроса
                    data: {
                        'genres': selectedGenres.join(',')
                    },
                    success: function () {
                        // Действия после успешной отправки данных
                        $('#genreModal').modal('hide');  // Закрытие модального окна
                    },
                    error: function () {
                        // Действия в случае ошибки
                        alert('Произошла ошибка при сохранении жанров.');
                    }
                });
            });
        });
    </script>
{% endblock %}

movies/main/templates/main/layout.html
<!DOCTYPE html>
<html lang="ru">
{%load static%}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}{%endblock%}</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    {% block style %}
        <link rel="stylesheet" href="{% static 'main/css/layout-style.css' %}">
    {% endblock %}
</head>

<body class="bg-dark text-light">
    <!-- Шапка с меню -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
        <div class="container">
            <a class="navbar-brand" href="{% url 'main:home' %}">MovieFinder</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:home' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:movies-rec' %}">Категории</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
    <li class="nav-item">
        {%if request.user.is_authenticated%}
            <li><a class="nav-link nav-link-divider" href="{% url 'user:logout' %}">Выйти</a></li>
            <li><a class="nav-link" href="{% url 'user:profile' %}"> Личный кабинет</a></li>
        {%else%}
            <li><a class="nav-link nav-link-divider" href="{% url 'user:login' %}">Вход</a></li>
            <li><a class="nav-link" href="{% url 'user:register' %}">Регистрация</a></li>
        {%endif%}
    </li>
</ul>
            </div>
        </div>
    </nav>

    {%block content%}

    {%endblock%}

</body>

</html>

movies/main/templates/main/movie-detail.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}Подробная информация о фильме{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/css/movie-datail-style.css' %}">
{% endblock %}

{% block content %}
<!-- Детальная информация о фильме -->
<div class="container mt-5">
    <div class="row">
        <div class="col-md-4">
            <img src="{{ film.poster }}" alt="Постер фильма" class="img-thumbnail">
        </div>
        <div class="col-md-8">
            <h1>{{ film.title }}</h1>
            <p class="lead">{{ film.description }}</p>
            <ul class="list-unstyled">
                <li><strong>Год:</strong> {{ film.year }}</li>
                <li><strong>Жанр:</strong>
                    {% for genre in film.genre.all %}
                    {{ genre.name }}
                    {% if not forloop.last %},{% endif %}
                    {% endfor %}
                </li>
                <li><strong>Режиссер:</strong>
                    {% for director in film.directors.all %}
                    {{ director.name }} {{ director.surname }}
                    {% if not forloop.last %},{% endif %}
                    {% endfor %}
                </li>
                <li><strong>В главных ролях:</strong>
                    {% for actor in film.actors.all %}
                    {{ actor.name }} {{ actor.surname }}
                    {% if not forloop.last %},{% endif %}
                    {% endfor %}
                </li>
            </ul>
            {%if request.user.is_authenticated %}
            <div class="btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary {% if enrollment and enrollment.isViewed %}active viewed-label{% else %}not-viewed-label{% endif %}">
                    <input type="checkbox" id="is-viewed-checkbox" autocomplete="off" {% if enrollment and enrollment.isViewed %}checked{% endif %}> Просмотрен
                </label>
            </div>
            {%endif %}
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $('#is-viewed-checkbox').change(function() {
            var isChecked = $(this).is(':checked');
            var filmSlug = '{{ film.slug }}';

            $.ajax({
                type: 'POST',
                url: '/film/' + filmSlug,
                data: {
                    'is_viewed': isChecked,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response) {
                    // Обработка успешного ответа, если необходимо
                },
                error: function(xhr, status, error) {
                    // Обработка ошибки, если необходимо
                }
            });
        });
    });
</script>
{% endblock %}

movies/main/templates/main/movie-list.html
{% for film in films %}
<div class="col-6 col-sm-4 col-md-3" data-genres="{{ film.genre.all|join:',' }}" data-year="{{ film.year }}">
    <div class="card bg-dark text-light mb-3" id="movie-card">
        <img src="{{ film.poster }}" class="card-img-top" data-bs-toggle="modal" data-bs-target="#movieModal{{ film.id }}" alt="{{ film.title }}">
        <div class="card-body">
            <h5 class="card-title">{{ film.title }}</h5>
        </div>
    </div>
</div>
{% endfor %}

movies/main/templates/main/movies-rec.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}MovieFinder{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/css/movies-rec-style.css' %}">
{% endblock %}

{% block content %}
<!-- Выдвигающееся меню -->
<div class="container mt-5">
    <div class="row">
        <div class="col-md-3" id="sidebar">
            <div class="d-flex">
                <h3 class="mt-3">Фильтры</h3>
                <button class="btn btn-secondary ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#filters" aria-expanded="true" aria-controls="filters">Показать/скрыть</button>
            </div>
            <div class="collapse show" id="filters">
                <div class="card bg-secondary mt-3">
                    <div class="card-body">
                        <h5>Жанр</h5>
                        <div class="filter-section scrollable-section expandable">
                            {% for genre in genres %}
                            <input type="checkbox" id="genre_{{ genre.id }}" class="genre-checkbox" name="genres" value="{{ genre.id }}" />
                            <label for="genre_{{ genre.id }}">{{ genre.name }}</label><br />
                            {% endfor %}
                        </div>

                        <h5 class="mt-3">Год</h5>
                        <div class="filter-section scrollable-section expandable">
                            {% for year in years %}
                            <input type="checkbox" id="year_{{ year }}" class="year-checkbox" name="years" value="{{ year }}" />
                            <label for="year_{{ year }}">{{ year }}</label><br />
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Постеры фильмов -->
        <div class="col-md-9">
            <div class="container position-relative">
                <div style="margin: 10px; display:inline-block, grid;">
                    <big>Лучшие фильмы</big>
                </div>
                <div class="row flex-row overflow-auto" id="moviesRow">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Movie Modal -->
{% for film in films %}
<div class="modal fade" id="movieModal{{ film.id }}" tabindex="-1" aria-labelledby="movieModalLabel{{ film.id }}" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content bg-dark text-light">
            <div class="modal-header">
                <h5 class="modal-title" id="movieModalLabel{{ film.id }}">{{ film.title }}</h5>
                <button type="button" class="btn-close text-light" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4">
                        <img src="{{ film.poster }}" class="img-fluid" alt="{{ film.title }}">
                    </div>
                    <div class="col-md-8">
                        <p>Оценка: {{ film.rating }}/10</p>
                        <p>Описание фильма: {{ film.description }}</p>
                        <a href="{% url 'main:movie-detail' film.slug %}" class="btn btn-light">Подробнее</a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

{% endfor %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script>
    // Функция для загрузки списка фильмов с сервера
    function loadMovies() {
        // Получаем выбранные жанры из отмеченных флажков
        var selectedGenres = Array.from(document.querySelectorAll('.genre-checkbox:checked')).map(function(checkbox) {
            return checkbox.value;
        });

        // Получаем выбранные годы из отмеченных флажков
        var selectedYears = Array.from(document.querySelectorAll('.year-checkbox:checked')).map(function(checkbox) {
            return checkbox.value;
        });

        // Отправляем AJAX-запрос на сервер для получения отфильтрованного списка фильмов
        $.ajax({
            type: 'GET',
            url: '{% url 'main:movie-list' %}',
            data: {
                'genres': selectedGenres.join(','), // Передаем выбранные жанры в параметре 'genres'
                'years': selectedYears.join(',') // Передаем выбранные годы в параметре 'years'
            },
            success: function(response) {
                // Обновляем содержимое элемента с идентификатором 'moviesRow' на странице
                $('#moviesRow').html(response);
            },
            error: function(xhr, status, error) {
                console.error(error);
            }
        });
    }

    // Функция для фильтрации фильмов
    function filterMovies() {
        loadMovies();
    }

    // Привязка обработчика события 'change' к флажкам жанров и годов
    $('.genre-checkbox, .year-checkbox').on('change', function() {
        filterMovies();
    });

    // Выполняем код при полной загрузке DOM-структуры страницы
    $(document).ready(function() {
        filterMovies();
    });
</script>
{% endblock %}